import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { FileText, Sparkles, LayoutDashboard, Trophy } from "lucide-react";

const features = [
  {
    icon: FileText,
    title: "Effortless Logging",
    description: "Interns log daily work in seconds with support for attachments, links, and quick notes.",
    color: "bg-blue-100 text-blue-600"
  },
  {
    icon: Sparkles,
    title: "AI Summaries",
    description: "Get automated weekly summaries and actionable next-step suggestions generated by AI.",
    color: "bg-purple-100 text-purple-600"
  },
  {
    icon: LayoutDashboard,
    title: "Manager Dashboard",
    description: "Track progress, engagement, and blockers in real-time with an intuitive command center.",
    color: "bg-emerald-100 text-emerald-600"
  },
  {
    icon: Trophy,
    title: "Gamification",
    description: "Boost engagement with progress streaks, badges, and automated encouragement triggers.",
    color: "bg-orange-100 text-orange-600"
  }
];

export default function LandingFeatures() {
  return (
    <section id="features" className="py-24 bg-white">
      <div className="container mx-auto px-6">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold font-heading text-slate-900 mb-4">
            Everything you need to scale your internship program
          </h2>
          <p className="text-lg text-slate-600">
            Stop chasing updates. ForgeFlow automates the busywork so you can focus on growing talent.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <Card key={index} className="border-none shadow-lg shadow-slate-200/50 hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
              <CardHeader>
                <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${feature.color}`}>
                  <feature.icon className="w-6 h-6" />
                </div>
                <CardTitle className="text-xl font-bold text-slate-900">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base text-slate-600 leading-relaxed">
                  {feature.description}
                </CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
